package ca.uwaterloo.ide

import com.ibm.wala.dataflow.IFDS.ISupergraph

trait Supergraph extends IdeTypes { // todo supergraph shouldn't extend Idetypes

  /**
   * The supergraph generated by WALA
   */
  val supergraph: ISupergraph[Node, Procedure]
}
