package ca.uwaterloo.ide

import com.ibm.wala.dataflow.IFDS.ISupergraph

trait SuperGraphTypes {

  /**
   * Type of a node in the WALA supergraph
   */
  type Node

  /**
   * Type of a procedure for the WALA supergraph
   */
  type Procedure

  /**
   * The supergraph generated by WALA
   */
  val supergraph: ISupergraph[Node, Procedure]
}
