package ca.uwaterloo.ide

import com.ibm.wala.dataflow.IFDS.ISupergraph

trait SuperGraphTypes {

  /**
   * Type of a node in the WALA supergraph
   */
  type Node

  /**
   * Type of a procedure for the WALA supergraph
   */
  type Procedure

  /**
   * The supergraph generated by WALA
   */
  val supergraph: ISupergraph[Node, Procedure]

  /**
   * The main method nodes that should be the entry points for the analysis
   */
  val entryPoints: Seq[Node]
}
